#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Verifica se bandas.json ou bandas/*.json foram modificados
if git diff --cached --name-only | grep -Eq '^bandas.json$|^bandas/.*\\.json$'; then
  npm run pre-commit
  echo "Não esqueça de atualizar estatísticas com 'npm run generate-statistics' após modificar bandas.json ou bandas/*.json."
  echo "Atualize a tag com 'npm run generate-tag'."
else
  echo "Nenhuma banda modificada, pulando validação."
fi
